services:
  iris:
    image: prophat-db:latest
    container_name: iris
    hostname: iris
    volumes:
      - /opt/prophat/persistent/db:/persistent
    ports:
      - "52773:52773"
      - "1972:1972"
    environment:
      - ISC_DATA_DIRECTORY=/persistent/iris
  
  webgateway:
    image: prophat-web:latest
    container_name: webgateway
    hostname: webgateway
    volumes:
      - /opt/prophat/persistent/web:/persistent
    ports:
      - "80:80"
    environment:
      - ISC_DATA_DIRECTORY=/persistent/iris